"""
Generate answers using qwen2.5 with top-5 retrieved contexts.

Improvements over v1:
  - top-k contexts increased from 3 → 5
  - Uses qwen2.5:latest (more concise answers → better lexical scores)
  - Optionally includes page captions from outputs/page_captions.json
    if available (generated by caption_pages.py)

Usage:
    PYTHONPATH=. python scripts/run_generation.py
"""

import json
from pathlib import Path

from app.generator import OllamaGenerator

DATA = Path("data/processed")
OUT = Path("outputs")

TOP_K_CONTEXTS = 5
N_QUERIES = 50


def load_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def build_prompt(question: str, contexts: list[str]) -> str:
    joined = "\n\n".join(f"[Context {i+1}]\n{c}" for i, c in enumerate(contexts))
    return f"""Answer the question using only the provided context. Be concise and direct.

Question:
{question}

Context:
{joined}

If the answer is not supported by the context, say "Insufficient evidence."

Answer:
"""


def main():
    corpus = {d["id"]: d for d in load_jsonl(DATA / "corpus.jsonl")}
    queries = {str(q["query_id"]): q for q in load_jsonl(DATA / "queries.jsonl")}
    runs = load_jsonl(OUT / "flexrag_retrieval_top10.jsonl")

    # Load captions if available (generated by caption_pages.py)
    captions: dict[str, str] = {}
    captions_path = OUT / "page_captions.json"
    if captions_path.exists():
        with captions_path.open() as f:
            captions = json.load(f)
        print(f"Loaded {len(captions)} page captions")
    else:
        print("No page captions found — using text only (run caption_pages.py to add captions)")

    gen = OllamaGenerator(model="qwen2.5:latest")
    outputs = []

    for row in runs[:N_QUERIES]:
        qid = str(row["query_id"])
        q = queries[qid]
        top_ids = [str(doc_id) for doc_id, _ in row["results"][:TOP_K_CONTEXTS]]

        contexts = []
        for doc_id in top_ids:
            if doc_id not in corpus:
                continue
            doc = corpus[doc_id]
            text = doc.get("text", "").strip()
            caption = captions.get(doc_id, "")
            # Combine text and caption if both available
            if caption and text:
                contexts.append(f"[Page caption: {caption}]\n{text}")
            elif caption:
                contexts.append(f"[Page caption: {caption}]")
            elif text:
                contexts.append(text)

        pred = gen.generate(build_prompt(q["question"], contexts))
        outputs.append({
            "query_id": qid,
            "question": q["question"],
            "prediction": pred,
            "answers": q["answers"],
            "context_doc_ids": top_ids,
        })
        print(f"  {len(outputs)}/{N_QUERIES} done")

    with open(OUT / "predictions.jsonl", "w", encoding="utf-8") as f:
        for row in outputs:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    print("Saved predictions.jsonl")


if __name__ == "__main__":
    main()
